{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "interactive-tsp.serviceAccountName" . }}
  labels:
{{ include "interactive-tsp.labels" . | nindent 4 }}
{{- end -}}
